### PR TITLE
Adding FreeBSD compatibility

### PR DESCRIPTION
**Pull request by interkosmos**
This pull requests removes a missing source file from the Makefile and adds FreeBSD compatibility. On FreeBSD, `make compile-linux` works as well.

### CODE REVIEW

**Comment by nalgeon** [comment]
`sqlite3-json1.c` is not missing. It is downloaded during the build process via the `download-external` make task.

**Comment by interkosmos** [comment]
I see. I’ve just used the [SQLite 3 port](https://www.freshports.org/databases/sqlite3/) which probably does not include the dependency. In this case, please ignore the Makefile commit.

**Comment by nalgeon** [comment]
I can't edit your changes. You'll have to revert the [62f32cd](https://github.com/nalgeon/sqlean/pull/60/commits/62f32cddd7998b4844f8375f542858798ddd9b69) commit.

**Comment by nalgeon** [comment]
Thanks!

**Pull request merged**
