### PR TITLE
add a new option for decimal separator

### PR DESCRIPTION
**Pull request by sf8321**
add a new option for decimal separator
add compiler option for cygwin gcc 
fix a Segmentation fault in vsvtabColumn with long double

### CODE REVIEW

**Comment by nalgeon** [comment]
Please do not include several unrelated changes in a single PR. Better to leave only the changes related to the decimal separator option. And please delete the commented-out code.

Also, I don't see any valid reason to changing the original code:

```c
long double dv, fp, ip;
dv = strtold(pCur->azVal[i], 0);
fp = modfl(dv, &ip);
```

Into this:

```c
double dv, fp, ip;
char* end;
dv = strtod(pCur->azVal[i], &end);
fp = modf(dv, &ip);
```

**Comment by sf8321** [comment]
Hallo,
yes i will separate it.
i think the crash (segmentation fault) have samething todo with this
https://sourceforge.net/p/mingw-w64/bugs/478/ or samething else in the gcc or/and libc
i go to a new perl 5.32 with gcc 8.5 and the problem i gone away

i your makefile you have a enviroment variables
$(SQLITE_RELEASE_YEAR), $(SQLITE_VERSION), $(SQLITE_BRANCH)
can give me the value of this or create same build.sh, build.bat where his varaiables have the correct values.
thanks

**Comment by nalgeon** [comment]
What segmentation fault are you talking about?

Environment variables values are in the [build.yml](https://github.com/nalgeon/sqlean/blob/main/.github/workflows/build.yml)

**Comment by sf8321** [comment]
The First time i Compiler it i use an older compiler which has a bug in the function modfl in newer compilers the bug is fixes. Look in the sourceforge Link above.

oh i can see the envy in the Build.yml.

is anything wrong with my pull request. Let me know.

**Comment by nalgeon** [comment]
Please revert the changes unrelated to the PR. Namely, changes to Makefile in the commit [3b5c13d](https://github.com/nalgeon/sqlean/pull/61/commits/3b5c13de289fa1d9715cb7c033845a20a0edcea1) and the whole [e965d92](https://github.com/nalgeon/sqlean/pull/61/commits/e965d9222f29fe4810662f745aca405f9f461ed7) commit.

**Comment by nalgeon** [comment]
Thanks!

**Pull request merged**
