### PR TITLE
feat: add ipaddr extension

### PR DESCRIPTION
**Pull request by vincentbernat**
This PR also contains PR #21. I'll rebase once its fate is decided.

### CODE REVIEW

**Comment by nalgeon** [comment]
Where is the source code coming from — is it yours or copied/adapted from somewhere? Will it work on Windows?

**Comment by vincentbernat** [comment]
It is my own code. I'll rebase and check if it compiles for Windows then.

**Comment by nalgeon** [comment]
I see. Thanks a lot for your contribution!

> check if it compiles for Windows

It does not:

```
src/sqlite3-ipaddr.c:9:10: fatal error: sys/socket.h: No such file or directory
```

I think that's OK. Please make it clear in `ipaddr.md` that the extension is not available for Windows (and remove it from the `compile-windows` task). Also, there is a misleading top-level comment in `sqlite3-ipaddr.c`. Otherwise, I'm ready to merge.

**Comment by vincentbernat** [comment]
Let me give another try. `inet_pton` and `inet_ntop` only needs `arpa/inet.h`. Let's see if it's available on Windows.

**Comment by nalgeon** [comment]
Nope:

```
src/sqlite3-ipaddr.c:9:10: fatal error: arpa/inet.h: No such file or directory
```

**Comment by vincentbernat** [comment]
OK, I give up for now. I have removed the compilation for Windows and added a note in the documentation.

**Comment by vincentbernat** [comment]
Sorry, I am too dumb, I did remove the extension for MacOS...

**Comment by nalgeon** [comment]
I've just merged the PR and released [0.9.1](https://github.com/nalgeon/sqlean/releases/tag/0.9.1). It's great to have your extension added to the pack! Thank you 🙏

**Pull request merged**
